FED-2444 Null safety preparation for conditional prop function calls
Workiva/over_react_codemod pull request #285
Opened 2024-04-10 19:39 UTC by aaronlademann-wf

## Motivation
Functions passed in as prop values are often null checked before being called using patterns that do not migrate nicely to null-safety - requiring the use of the `!` assertion like so:

```dart
if (props.onClick != null) {
  props.onClick!(event);
}
// or
props.onClick != null && props.onClick!(event);
```

## Changes
1. Add a suggestor that removes the separate conditional null check and instead adds a null-aware `?` operator
1. Add the suggestor to the existing `null_safety_prep` executable.
1. Write tests.

### What it does
**Before**
```dart
if (props.onClick != null) {
  props.onClick(event);
}
// or
props.onClick != null && props.onClick(event);
```

**After**
```dart
props.onClick?.call(event);
```

2024-04-10 19:41 UTC, aviary-wf commented
## Security Insights
No security relevant content was detected by automated scans.

## Action Items
* Review PR for [security impact](https://wiki.atl.workiva.net/display/SECURITY/Development+Security+Review+Guidelines); comment "security review required" if needed or unsure
* Verify [`aviary.yaml`](https://wiki.atl.workiva.net/pages/viewpage.action?pageId=42762752#SecurityInsightFramework&Tooling-ConfiguringAviary) coverage of security relevant code
---
_Questions or Comments? Reach out on Slack: #support-infosec._

2024-04-11 16:28 UTC, greglittlefield-wf requested changes
Looking good, left some comments on cases to handle and tests

2024-04-11 16:28 UTC, greglittlefield-wf commented on test/dart3_suggestors/null_safety_prep/fn_prop_null_aware_call_suggestor_test.dart
> +    });
Could we also add test cases that
- if-checks that don't involve props aren't updated (and the codemod skips over them without throwing)
- then statements that `return` something aren't updated
- then statements that do something besides call the prop aren't updated

2024-04-11 19:08 UTC, aaronlademann-wf commented
All feedback addressed!

2024-04-16 23:22 UTC, greglittlefield-wf requested changes
Thanks for addressing that feedback! Just one more small comment, otherwise LGTM; I also tested it locally and it works great!

2024-04-16 23:22 UTC, greglittlefield-wf commented on lib/src/dart3_suggestors/null_safety_prep/fn_prop_null_aware_call_suggestor.dart
> +      return null;
I think this check isn't as specific as it should be, and due to the `thisOrAncestorOfType`, might cause cases to get skipped if they're nested. For example, I'd expect this to get skipped with the current logic
```dart
if (condition) {
  if (props.onClick != null) props.onClick(e)
} else {}
```

Could we just check the parent directly instead?
```suggestion
    if (ifStatement.parent.tryCast<IfStatement>()?.elseStatement ==
        ifStatement) {
      // ifStatement is an else-if
      return null;
    }
```

2024-04-18 17:06 UTC, greglittlefield-wf approved these changes
+10

2024-04-18 17:56 UTC, greglittlefield-wf approved these changes
+10

@Workiva/release-management-p

2024-04-18 17:57 UTC, rmconsole-wf approved these changes
+1 from RM

2024-04-18 17:57 UTC, merged